services:
  - type: web
    name: adotapet-web
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    healthCheckPath: /health.php
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: adotapet-db
          property: connectionString
      - key: RUN_MIGRATIONS
        value: "1"

databases:
  - name: adotapet-db
    plan: free
    databaseName: adota_pet
    user: adota_pet
