services:
  - type: web
    name: adotapet-web
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    envVars:
      - key: DB_HOST
        fromService:
          name: adotapet-db
          type: mysql
          property: host
      - key: DB_USER
        fromService:
          name: adotapet-db
          type: mysql
          property: user
      - key: DB_PASS
        fromService:
          name: adotapet-db
          type: mysql
          property: password
      - key: DB_NAME
        fromService:
          name: adotapet-db
          type: mysql
          property: database

databases:
  - name: adotapet-db
    plan: starter
    databaseName: adota_pet
